-- Feature leaderboard: owner-curated feature ideas + per-user upvotes.
--
-- The Features menu (top toolbar, next to Help) opens a popup with a
-- "Suggest a feature" button (emails the owner — unchanged behaviour) and an
-- upvotable leaderboard. Leaderboard entries are NOT user-submitted: the owner
-- curates them in the Supabase dashboard from emailed suggestions. Users only
-- read the board and upvote.
--
-- Two tables:
--   feature_suggestions       — curated leaderboard entries (shared / global)
--   feature_suggestion_votes  — one row per user per upvote
--
-- All additive — new tables, function, trigger. No destructive changes.
-- Applied 2026-05-17 via Supabase MCP.

-- ── 1. feature_suggestions ──────────────────────────────────────────────
-- Deliberately has NO user_id: this is a shared/global table that every
-- signed-in user reads in full. A considered deviation from the Pattern-A
-- (user_id = auth.uid()) convention, in the spirit of `subscriptions`
-- (select-only RLS, writes via the service role only).
create table public.feature_suggestions (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  status      text not null default 'open'
              check (status in ('open','planned','in_progress','shipped')),
  vote_count  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.feature_suggestions enable row level security;

-- Every signed-in user reads the whole board. No insert/update/delete
-- policies — only the Supabase dashboard / service role can write, which is
-- how the owner curates entries.
create policy feature_suggestions_select on public.feature_suggestions
  for select using (true);

-- ── 2. feature_suggestion_votes ─────────────────────────────────────────
-- One upvote per user per suggestion, enforced by the composite primary key.
create table public.feature_suggestion_votes (
  suggestion_id bigint not null references public.feature_suggestions(id) on delete cascade,
  user_id       uuid   not null references auth.users(id) on delete cascade,
  created_at    timestamptz not null default now(),
  primary key (suggestion_id, user_id)
);

create index feature_suggestion_votes_user_id_idx
  on public.feature_suggestion_votes(user_id);

alter table public.feature_suggestion_votes enable row level security;

-- Pattern A, scoped to the user's own votes (select / insert / delete; no update).
create policy feature_suggestion_votes_select on public.feature_suggestion_votes
  for select using (user_id = auth.uid());
create policy feature_suggestion_votes_insert on public.feature_suggestion_votes
  for insert with check (user_id = auth.uid());
create policy feature_suggestion_votes_delete on public.feature_suggestion_votes
  for delete using (user_id = auth.uid());

-- ── 3. Vote-count trigger ───────────────────────────────────────────────
-- Keeps feature_suggestions.vote_count authoritative so the leaderboard is a
-- single ordered read (no need to fetch every user's votes). SECURITY DEFINER
-- because the voting user neither owns the feature_suggestions row nor has any
-- UPDATE policy on that table.
create or replace function public.feature_suggestion_vote_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.feature_suggestions
      set vote_count = vote_count + 1, updated_at = now()
      where id = new.suggestion_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.feature_suggestions
      set vote_count = greatest(vote_count - 1, 0), updated_at = now()
      where id = old.suggestion_id;
    return old;
  end if;
  return null;
end;
$$;

create trigger feature_suggestion_votes_count_trg
  after insert or delete on public.feature_suggestion_votes
  for each row execute function public.feature_suggestion_vote_count();

-- The function is SECURITY DEFINER and lives in `public`, so PostgREST would
-- otherwise expose it as a callable RPC. Revoke direct EXECUTE — the trigger
-- still fires (trigger invocation does not consult the EXECUTE privilege).
revoke execute on function public.feature_suggestion_vote_count()
  from public, anon, authenticated;
