-- Accounting integration: QuickBooks Online + Xero one-way invoice push.
--
-- Two tables:
--   accounting_connections  — OAuth state, one row per (user_id, provider). The
--     token columns (access_token_enc / refresh_token_enc) are AES-GCM encrypted
--     at rest and HIDDEN from the client via column-level grants — only the
--     service role (edge functions) ever reads them. Mirrors the subscriptions
--     table's "service-role writes, owner reads" model (SCHEMA.md § 3.17).
--   accounting_invoice_links — maps an order to the external invoice it was
--     pushed to (for the "Synced" chip, deep link, and re-push dedupe).
--
-- Additive only. RLS uses the InitPlan-optimised (select auth.uid()) form.

-- ── accounting_connections ────────────────────────────────────────────────
create table public.accounting_connections (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null references auth.users(id) on delete cascade,
  provider          text not null check (provider in ('quickbooks','xero')),
  access_token_enc  text,                 -- AES-GCM, iv‖ciphertext base64; service-role only
  refresh_token_enc text,                 -- AES-GCM, iv‖ciphertext base64; service-role only
  expires_at        timestamptz,          -- access-token expiry
  realm_id          text,                 -- QuickBooks Online company id
  tenant_id         text,                 -- Xero tenant id
  org_name          text,                 -- connected company / org name (display)
  default_tax_code  text,                 -- provider tax code/rate id used on pushed invoice lines
  status            text not null default 'connected'
                    check (status in ('connected','revoked','error')),
  connected_at      timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (user_id, provider)
);

comment on table public.accounting_connections is
  'OAuth connections to QuickBooks Online / Xero. Token columns are AES-GCM encrypted and hidden from the client via column grants; only the service role (edge functions) reads them.';

alter table public.accounting_connections enable row level security;

-- RLS: owner can SELECT their own row(s). No insert/update/delete policies —
-- the edge functions write via the service-role key (bypasses RLS).
create policy "owner can read own accounting connection"
  on public.accounting_connections for select
  using (user_id = (select auth.uid()));

-- Column-level grants: hide the encrypted token columns from the client.
-- A client select=* is denied at the column level; the frontend selects only
-- the safe columns explicitly. service_role keeps full access for the fns.
revoke all on public.accounting_connections from anon, authenticated;
grant select (id, user_id, provider, realm_id, tenant_id, org_name,
              default_tax_code, status, expires_at, connected_at, updated_at)
  on public.accounting_connections to authenticated;
grant all on public.accounting_connections to service_role;

-- ── accounting_invoice_links ──────────────────────────────────────────────
create table public.accounting_invoice_links (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users(id) on delete cascade,
  order_id        bigint not null references public.orders(id) on delete cascade,
  provider        text not null check (provider in ('quickbooks','xero')),
  external_id     text not null,          -- QBO Invoice.Id / Xero InvoiceID
  external_number text,                   -- DocNumber / InvoiceNumber
  external_url    text,                   -- deep link to view in QB/Xero
  status          text,                   -- last-known state at push time (not synced back)
  pushed_at       timestamptz not null default now(),
  unique (user_id, order_id, provider)
);

comment on table public.accounting_invoice_links is
  'Maps a ProCabinet order to the external invoice it was pushed to. Owner-readable; written by the push edge function (service role).';

create index accounting_invoice_links_order_id_idx on public.accounting_invoice_links(order_id);

alter table public.accounting_invoice_links enable row level security;

-- RLS: owner can SELECT. Writes happen via the service role in the push
-- function (external system is the source of truth), so no write policies.
create policy "owner can read own invoice links"
  on public.accounting_invoice_links for select
  using (user_id = (select auth.uid()));

grant all on public.accounting_invoice_links to service_role;
