-- Quote & Order overhaul — shareable live pages, item toggles, spec editing,
-- card payments (Stripe Connect), line-item photos, and customer chat.
--
-- Phase 1 of the build (see ~/.claude/plans/i-want-to-do-polished-micali.md § 9).
-- ADDITIVE ONLY — new nullable columns (safe defaults) + new tables. Nothing is
-- dropped or back-filled destructively. RLS uses the InitPlan-optimised
-- (select auth.uid()) form (SCHEMA.md § 4, Pattern A).
--
-- Customer-facing access is UNAUTHENTICATED and goes exclusively through edge
-- functions using the service-role key (mirrors the accounting/stripe model) —
-- a logged-out customer never touches PostgREST, so these tables need NO anon
-- RLS policies. Owner (authenticated) policies are the standard Pattern A.
--
-- Decision note: the chat table is named `customer_messages` (client-scoped), not
-- the plan's tentative `quote_messages` — a conversation spans all of a client's
-- quotes/orders and is surfaced per-client in the Clients tab (Option D).

-- ════════════════════════════════════════════════════════════════════════════
-- 1. quotes — shareable live-page state
-- ════════════════════════════════════════════════════════════════════════════
alter table public.quotes
  add column if not exists share_token       text,
  add column if not exists share_settings    jsonb not null default '{}'::jsonb,
  add column if not exists viewed_at          timestamptz,
  add column if not exists accepted_at         timestamptz,
  add column if not exists accepted_snapshot   jsonb;

-- Unique, but many NULLs (only shared quotes get a token) → partial unique index.
create unique index if not exists quotes_share_token_key
  on public.quotes(share_token) where share_token is not null;

comment on column public.quotes.share_settings is
  'Customer-facing controls set in the Share panel: { allow_select bool, allow_edit bool, accept_payment bool, deposit_pct numeric, expires_at timestamptz }. Smart Link mode was dropped — no present_mode.';
comment on column public.quotes.accepted_snapshot is
  'Frozen line state the customer accepted (included lines + their edited specs + totals) — the source of truth for the order created on payment.';
-- status gains the live states: draft | sent | viewed | accepted | declined | expired.
-- (status is a plain text column — no check constraint to alter.)

-- ════════════════════════════════════════════════════════════════════════════
-- 2. orders — share/view + balance-payment link
-- ════════════════════════════════════════════════════════════════════════════
alter table public.orders
  add column if not exists share_token    text,
  add column if not exists share_settings jsonb not null default '{}'::jsonb,
  add column if not exists viewed_at       timestamptz;

create unique index if not exists orders_share_token_key
  on public.orders(share_token) where share_token is not null;

-- status gains: ... | deposit_paid (between confirmed and production).

-- ════════════════════════════════════════════════════════════════════════════
-- 3. quote_lines / order_lines — per-line customer controls
-- ════════════════════════════════════════════════════════════════════════════
alter table public.quote_lines
  add column if not exists optional          boolean not null default false,  -- customer may exclude
  add column if not exists customer_editable boolean not null default false,  -- customer may edit spec
  add column if not exists customer_included boolean not null default true,   -- current include state
  add column if not exists customer_price    numeric;                         -- all-in customer-facing price (post-markup), snapshotted at share time

alter table public.order_lines
  add column if not exists optional          boolean not null default false,
  add column if not exists customer_editable boolean not null default false,
  add column if not exists customer_included boolean not null default true,
  add column if not exists customer_price    numeric;

-- `customer_price` is the all-in per-line price the CUSTOMER sees (their share of
-- materials + labour + markup, pre-tax). Written by the business app at share
-- time from calcCBLine, so the customer page never receives the business's cost
-- inputs (material costs, labour rate, markup %) — it only sums these safe
-- figures. Editing a spec on the live page marks the line "price to confirm"
-- until the business re-snapshots (live edit-reprice needs the costing ported
-- server-side — a later sub-step).

-- ════════════════════════════════════════════════════════════════════════════
-- 4. line_photos — photos on quote/order lines and cabinet-library templates
--    Files live in the existing public `business-assets` bucket (reuses
--    _uploadLogoAsset). This table just records the path + ordering.
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.line_photos (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  owner_kind   text not null check (owner_kind in ('quote_line','order_line','cabinet_template')),
  owner_id     bigint not null,                 -- FK enforced in app (polymorphic), scoped by user_id
  storage_path text not null,                   -- path within the business-assets bucket
  caption      text,
  position     integer not null default 0,
  created_at   timestamptz not null default now()
);

comment on table public.line_photos is
  'Photos attached to a quote line, order line, or cabinet template. Rendered on cards, the live customer page, and the order/quote PDFs. Files in the business-assets bucket; this row holds the path + position.';

create index if not exists line_photos_owner_idx on public.line_photos(owner_kind, owner_id);
create index if not exists line_photos_user_idx  on public.line_photos(user_id);

alter table public.line_photos enable row level security;
create policy "owner can read line photos"   on public.line_photos for select using (user_id = (select auth.uid()));
create policy "owner can insert line photos" on public.line_photos for insert with check (user_id = (select auth.uid()));
create policy "owner can update line photos" on public.line_photos for update using (user_id = (select auth.uid()));
create policy "owner can delete line photos" on public.line_photos for delete using (user_id = (select auth.uid()));
-- service role reads to embed photos in the public page / PDF rendered server-side.
grant all on public.line_photos to service_role;

-- ════════════════════════════════════════════════════════════════════════════
-- 5. customer_messages — two-way chat (Clients-tab Option D + customer widget)
--    Owner (business) reads/writes via JWT. The customer posts from the live
--    page widget via an edge function (service role), resolved from the quote's
--    share_token → client_id.
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.customer_messages (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,   -- business owner
  client_id   bigint not null references public.clients(id) on delete cascade,
  quote_id    bigint references public.quotes(id) on delete set null,       -- optional context
  order_id    bigint references public.orders(id) on delete set null,       -- optional context
  sender      text not null check (sender in ('business','customer')),
  body        text not null,
  read_at     timestamptz,                       -- when the recipient read it (drives unread badges)
  created_at  timestamptz not null default now()
);

comment on table public.customer_messages is
  'Per-client conversation thread. Business reads/writes via JWT (Pattern A); the customer posts from the live-page chat widget via an edge function (service role) keyed by the quote share_token.';

create index if not exists customer_messages_client_idx on public.customer_messages(client_id, created_at);
create index if not exists customer_messages_user_idx   on public.customer_messages(user_id, created_at);

alter table public.customer_messages enable row level security;
create policy "owner can read messages"   on public.customer_messages for select using (user_id = (select auth.uid()));
create policy "owner can insert messages" on public.customer_messages for insert with check (user_id = (select auth.uid()));
create policy "owner can update messages" on public.customer_messages for update using (user_id = (select auth.uid()));
create policy "owner can delete messages" on public.customer_messages for delete using (user_id = (select auth.uid()));
-- customer-posted messages are inserted by the edge function as service_role.
grant all on public.customer_messages to service_role;

-- ════════════════════════════════════════════════════════════════════════════
-- 6. stripe_accounts — the business's connected Stripe (Connect) account
--    Owner reads status; the connect/webhook edge functions write (service role).
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.stripe_accounts (
  user_id            uuid primary key references auth.users(id) on delete cascade,
  stripe_account_id  text not null unique,        -- acct_… (Connect account; not a secret)
  charges_enabled    boolean not null default false,
  payouts_enabled    boolean not null default false,
  details_submitted  boolean not null default false,
  country            text,
  default_currency   text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

comment on table public.stripe_accounts is
  'The business owner''s Stripe Connect account. Customer card payments settle into this account; ProCabinet takes an application fee. Written by the connect-onboard / connect-status / webhook edge functions (service role); owner reads status.';

alter table public.stripe_accounts enable row level security;
create policy "owner can read own stripe account"
  on public.stripe_accounts for select using (user_id = (select auth.uid()));
grant all on public.stripe_accounts to service_role;

-- ════════════════════════════════════════════════════════════════════════════
-- 7. payments — customer card payments (deposit / balance / full)
--    Created + updated by the quote-pay edge function and its webhook (service
--    role). Owner reads (dashboards, "deposit paid" chips, balance tracking).
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.payments (
  id                     bigint generated by default as identity primary key,
  user_id                uuid not null references auth.users(id) on delete cascade,  -- business owner (payee)
  quote_id               bigint references public.quotes(id) on delete set null,
  order_id               bigint references public.orders(id) on delete set null,
  stripe_payment_intent  text unique,
  stripe_checkout_session text,
  kind                   text not null check (kind in ('deposit','balance','full')),
  amount                 numeric not null default 0,     -- total charged (gross)
  application_fee        numeric not null default 0,     -- ProCabinet's platform fee
  currency               text not null default 'gbp',
  status                 text not null default 'pending', -- pending | succeeded | failed | refunded
  customer_email         text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

comment on table public.payments is
  'Customer card payments via Stripe Connect (direct charges into the business account with an application_fee). Written by the quote-pay function + webhook (service role); owner reads.';

create index if not exists payments_user_idx  on public.payments(user_id, created_at);
create index if not exists payments_order_idx on public.payments(order_id);
create index if not exists payments_quote_idx on public.payments(quote_id);

alter table public.payments enable row level security;
create policy "owner can read own payments"
  on public.payments for select using (user_id = (select auth.uid()));
grant all on public.payments to service_role;
