-- Google Calendar connection store (GC.1) — one row per user, encrypted
-- OAuth tokens (AES-GCM via the shared ACCOUNTING_TOKEN_KEY, same treatment
-- as accounting_connections § 3.21). Written exclusively by the gcal-oauth /
-- gcal-sync edge functions (service role); the client reads only the
-- non-secret columns to show connection status.

create table if not exists public.gcal_connections (
  id                 bigint generated by default as identity primary key,
  user_id            uuid not null unique references auth.users(id) on delete cascade,
  calendar_id        text not null default 'primary',
  google_email       text,                     -- best-effort display label
  access_token_enc   text,
  refresh_token_enc  text,
  expires_at         timestamptz,              -- access-token expiry
  status             text not null default 'connected',
  last_synced_at     timestamptz,
  connected_at       timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists gcal_connections_user_idx on public.gcal_connections(user_id);

alter table public.gcal_connections enable row level security;

-- Owner may READ (status surface; tokens are AES-GCM blobs, useless without
-- the server-side key). All writes go through service-role edge functions.
drop policy if exists "owner can read gcal connection" on public.gcal_connections;
create policy "owner can read gcal connection"
  on public.gcal_connections for select using (user_id = (select auth.uid()));
