-- Schedule tasks (SV.1) — standalone timed tasks on the Schedule tab.
-- Non-order work (deliveries, site visits, admin...) that renders alongside
-- scheduler-placed order blocks in the Day/Week/Month views. Single task
-- type by design (2026-07-11 decision) — no category column.
-- gcal_* columns are phase-2-ready slots for the Google Calendar 2-way sync.

create table if not exists public.schedule_tasks (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users(id) on delete cascade,
  title          text not null default '',
  notes          text,
  start_at       timestamptz not null,
  end_at         timestamptz not null,
  all_day        boolean not null default false,
  done           boolean not null default false,
  gcal_event_id  text,                      -- Google Calendar event id (phase 2)
  gcal_synced_at timestamptz,               -- last successful GCal sync (phase 2)
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists schedule_tasks_user_start_idx
  on public.schedule_tasks (user_id, start_at);

alter table public.schedule_tasks enable row level security;

-- Pattern A — direct ownership. InitPlan-optimised auth.uid() form.
drop policy if exists "owner can read schedule tasks" on public.schedule_tasks;
create policy "owner can read schedule tasks"
  on public.schedule_tasks for select using (user_id = (select auth.uid()));

drop policy if exists "owner can insert schedule tasks" on public.schedule_tasks;
create policy "owner can insert schedule tasks"
  on public.schedule_tasks for insert with check (user_id = (select auth.uid()));

drop policy if exists "owner can update schedule tasks" on public.schedule_tasks;
create policy "owner can update schedule tasks"
  on public.schedule_tasks for update using (user_id = (select auth.uid()));

drop policy if exists "owner can delete schedule tasks" on public.schedule_tasks;
create policy "owner can delete schedule tasks"
  on public.schedule_tasks for delete using (user_id = (select auth.uid()));

-- Workday start time (SV.2) — anchors the scheduler's per-day hour segments
-- (and timed order blocks in the Day/Week grids) at a time of day.
alter table public.business_info
  add column if not exists workday_start_time text not null default '08:00';

comment on column public.business_info.workday_start_time is
  'HH:MM local time the workday begins; anchors order hour-blocks in the Schedule day/week views.';
